// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgNwAoRQ_GvKqcPTKMs81jOqqWBPNdIxk',
    appId: '1:663649567318:web:7e572a27dc8f7e78edf1f7',
    messagingSenderId: '663649567318',
    projectId: 'cinebooking-eb27e',
    authDomain: 'cinebooking-eb27e.firebaseapp.com',
    storageBucket: 'cinebooking-eb27e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ddxUQncR5Y_Qy7ay9EvzUv5UXxcEmDY',
    appId: '1:663649567318:android:524fb8800d7441a0edf1f7',
    messagingSenderId: '663649567318',
    projectId: 'cinebooking-eb27e',
    storageBucket: 'cinebooking-eb27e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs6B8xKkvD-J0AuvKervWT4nNofDOrSo0',
    appId: '1:663649567318:ios:4d9bfcdf6e43c7e9edf1f7',
    messagingSenderId: '663649567318',
    projectId: 'cinebooking-eb27e',
    storageBucket: 'cinebooking-eb27e.firebasestorage.app',
    iosBundleId: 'com.example.cinebooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs6B8xKkvD-J0AuvKervWT4nNofDOrSo0',
    appId: '1:663649567318:ios:4d9bfcdf6e43c7e9edf1f7',
    messagingSenderId: '663649567318',
    projectId: 'cinebooking-eb27e',
    storageBucket: 'cinebooking-eb27e.firebasestorage.app',
    iosBundleId: 'com.example.cinebooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgNwAoRQ_GvKqcPTKMs81jOqqWBPNdIxk',
    appId: '1:663649567318:web:43df2611ca176299edf1f7',
    messagingSenderId: '663649567318',
    projectId: 'cinebooking-eb27e',
    authDomain: 'cinebooking-eb27e.firebaseapp.com',
    storageBucket: 'cinebooking-eb27e.firebasestorage.app',
  );
}
